### PR TITLE
Fix AI naut selection

### PR DESCRIPTION
**Pull request by hweimer**
Fixes a bug in the AI naut selection code that led to the Soviet side selecting from U.S. candidates.

### CODE REVIEW

**Comment by peyre** [comment]
Good work!

**Comment by peyre** [comment]
Good work there!  Say, is there an easy way to add a Race characteristic to crew.json, or does each line have to be added manually?  In case someone decides to address #293, it would make the data side easier to do.

    On Saturday, January 20, 2024 at 03:31:07 AM PST, Hendrik W. ***@***.***> wrote:  
 
 
Fixes a bug in the AI naut selection code that led to the Soviet side selecting from U.S. candidates.

You can view, comment on, or merge this pull request online at:

  https://github.com/raceintospace/raceintospace/pull/832

Commit Summary
   
   - e817ba3 Fix AI naut selection

File Changes 
 
(1 file)
   
   -  M src/game/aipur.cpp (2) 

Patch Links:
   
   - https://github.com/raceintospace/raceintospace/pull/832.patch
   - https://github.com/raceintospace/raceintospace/pull/832.diff

**Comment by hweimer** [comment]
Adding a Race field is really easy with a decent editor, as is adding it to the data structures of the game. The most difficult step is creating the necessary images and making sure they show up in the right place.

**Comment by peyre** [comment]
I have images for them, incidentally.

**Pull request merged**
