### PR TITLE
Improved save game handling

### PR DESCRIPTION
**Pull request by hweimer**
PBEM saving now uses the same code as regular saving, i.e., also showing the list of available saved game names. Filenames are now derived from the actual title of the game, altough existing BUZZ?.SAV filenames continue to be used. Finally, PBEM games are shown in yellow in the Time Capsule screen. Partially addresses #438.

### CODE REVIEW

**Comment by rnyoakum** [comment]
Sorry for the delay in reviewing this. Three points worth looking at:

First, when you replace the save code with the SaveGame function in FileAccess, you remove the GUI code
```
            InBox(209, 64, 278, 72);	
            delay(250);
```

at the top as well. This isn't important, but might be nice to keep.

Second, calling FileAccess(2) won't display the PBEM files because of a preexisting bug. In FileAccess:
```
    //sp. case -> no regular save off mail/modem game
    if ((mode == 0 || mode == 1) && (MAIL != -1 || Option != -1)) {
        sc = 2;
    }

    // TODO: Since mode == 2 is checked later, when it cannot occur,
    // I'm guessing this is some kind of hack added at a later time.
    // This needs to be deciphered and better documented. -- rnyoakum
    if (mode == 2) {
        mode = 0;
        sc = 1;  //only allow mail save
    }
...
    saveType = SAVEGAME_Normal;

    if (Option != -1) {
        saveType = SAVEGAME_Modem;
    } else if (mode == 2) {
        saveType = SAVEGAME_PlayByMail;
    }

    std::vector<SFInfo> savegames = GenerateTables(saveType);
``` 

As you can see, the saveType will be `SAVEGAME_Normal` when `GenerateTables` is called. Moving the saveType assignment up would probably work fine.

Third, combining the savegame code from FileAccess with the PBEM save function you had written means that the new `SaveGame` function contains the call 
```
        EndOfTurnSave((char *) Data, sizeof(struct Players));
```

which updates the save to the current game state. This is correct for the PBEM save, but is new behavior for 'normal' saves, which date to the beginning of the turn. I don't think you intended that.

**Comment by hweimer** [comment]
Thank you for your review. I have restored the display of the pressed button (i.e., your first comment), but for the other two I have some questions/comments:

2. GenerateTables returns all save files when called with SAVEGAME_Normal. Since it is no longer possible to have two games with the same name (because they would get written to the same file), it is probably better to always list all game names, even when they don't match the current game mode.

3. You are right that the commit changes the behavior for normal saves. However, shouldn't it be the case that the current state of the game gets saved? Saving at the beginning of the turn would give you an undo option for things where this should not be available (like R&D rolls).

**Comment by rnyoakum** [comment]
> GenerateTables returns all save files when called with SAVEGAME_Normal. Since it is no longer possible to have two games with the same name (because they would get written to the same file), it is probably better to always list all game names, even when they don't match the current game mode.

That's a good point I hadn't considered. It's fine with me; I just wanted to make sure there's not any _unexpected_ behavior. I'll look into color-coding the save names so they can be easily distinguished.

> You are right that the commit changes the behavior for normal saves. However, shouldn't it be the case that the current state of the game gets saved? Saving at the beginning of the turn would give you an undo option for things where this should not be available (like R&D rolls).

It would, but you could just as easily save-scum with the proposed behavior; RIS works on the honor system anyways. I'm a little concerned changing the behavior will cause some errors to pop up, but I think I dealt with most of those working with the Autosave. Knowing that you intend the new behavior, I'm ambivalent about the change, but it is a big one. On gameplay issues like this I defer to @peyre. Leon?

**Comment by peyre** [comment]
Oh I don't know.  I've always been content with how the game handles saves, but if you think a change would improve it, I wouldn't object.

**Comment by rnyoakum** [comment]
Overall, the commit adds value, so I'm going to merge it. I may add an option to toggle between save policies. If people try the game and don't like the save policy, or if it causes problems, it wouldn't be hard to revert.

**Pull request merged**
