### PR TITLE
Move help entries to JSON format

### PR DESCRIPTION
**Pull request by hweimer**
Moves the help entries to a human-editable JSON format. Since JSON does not allow multi-line strings, the text for the entries is stored as a vector of strings with each line being one element of the vector. Yet another step towards resolving #3.

### CODE REVIEW

**Comment by peyre** [comment]
Am I right in thinking this obsoletes the utility to modify the help file?

https://sourceforge.net/p/raceintospace/mailman/raceintospace-cvs/thread/E1H9PO6-0002Rt-VX%40mail.sourceforge.net/

**Comment by hweimer** [comment]
Oh, there was a tool to edit the old help file? The only ones I can see is for movies and news, and there is the data_decoder tool, but the latter is only for viewing and not editing data.

**Comment by peyre** [comment]
Someone (whom Ryan knows?) created one on SourcerForge.  I'm not sure what prompted him to do it, but it's been a big help.

**Comment by peyre** [comment]
Uh oh, the new JSON format seems to have removed blank lines from the help file.  I wouldn't object to fixing it myself if I knew how to do it properly.

Add a space
Spaces

**Comment by hweimer** [comment]
Can you open a separate issue for that? The problem is that empty lines are being removed by data_decoder. Do you have a link to the program you used for editing the old help file? Might be better at extracting the data.

**Comment by peyre** [comment]
Sure, I'd be glad to.  I can find the link this evening.

**Pull request merged**
