### PR TITLE
Pbem flag

### PR DESCRIPTION
**Pull request by rnyoakum**
Disables Play-by-Email by default unless a "-DPBEM=ON" flag is supplied to cmake

### CODE REVIEW

**Comment by peyre** [comment]
Am I right in thinking this is added as an option in Advanced Preferences?  I like that idea, but my preference would be to turn PBEM on by default.

**Comment by rnyoakum** [comment]
No, this wouldn't be in Advanced Preferences. This would disable PBEM unless it was built using a cmake flag - this approach  sets a flag to the compiler, so it's not configurable post-build. @pemensik suggested the approach since there aren't enough checks to verify that a save game is safe to use. I built it following the discussion in #416.

I didn't commit this because
1. If you don't think there should be any delay in adding PBEM - users should be warned that there are security risks, and trusted to make wise decisions - then this is counterproductive.
2. It should be tested on Windows to make sure it builds correctly there, as well. 

That's why it's still a pull request.

If not using this code, there should be a commit that would launch a Help popup confirmation any time someone tries to load a PBEM game, as @hweimer suggested this morning (it's a good idea).

**Comment by peyre** [comment]
Oh, I see.  I'm excited that PBEM is back and appears to work.  I like Hendrik's idea of leaving it enabled but with a warning that it's experimental and lacks security measures (I812).  However I'm light on best programming practices, so if you folks thing we should hold back on mail games for now, I'd be ok with it.  You're the experts.

You make a good point there about testing it on Windows!  That would be a good idea in any case - come to think of it, I think Hendrik and I were both testing it on Linux.

Some time back I updated the Ubuntu compiling instructions in README.md so anyone can do it.  I've tried following the Windows instructions but couldn't get them to work.  Do you think you could update the Windows instructions?

**Comment by pemensik** [comment]
It disables main menu correctly on my build. I haven't checked it more, but it sems it work.

**Comment by peyre** [comment]
Aw, PBEM is gone now.  I has a sad.  :(

**Comment by peyre** [comment]
You're sure we can't make it available with an "experimental" disclaimer?

**Comment by rnyoakum** [comment]
Personally, I think it's best not to include the feature when the feature isn't safe. If someone wants experimental features, the best place is download the active development on Github. Rather than enable the PBEM for the release, I suggest adding a comment in the README about PBEM's availability and how to build RIS with that feature. Later, after the release, security can be added to ensure PBEM is safe(r) and the feature enabled by default for the next release.

**Comment by peyre** [comment]
Ok, maybe we can make PBEM available in release 2.1.

**Pull request merged**
