### PR TITLE
Fix macOS build errors

### LINKED ISSUE #364: Undefined symbols when linking game_test on macOS
Using the latest raceintospace code from yesterday 2020-06-03 (8ff7814d5e2b6e73a817ead6c76eeb8823d4e3d7) and the patch for #307 I submitted in #363 the game_test executable fails to link:

```
[ 55%] Linking CXX executable ../../game_test
cd /opt/local/var/macports/build/_Users_rschmidt_macports_macports-ports-svn-trunk-new_games_raceintospace/raceintospace/work/build/src/game && /opt/local/bin/cmake -E cmake_link_script CMakeFiles/game_test.dir/link.txt --verbose=ON
/usr/bin/clang++  -pipe -Os -std=c++11 -DNDEBUG -I/opt/local/include -stdlib=libc++ -arch x86_64 -mmacosx-version-min=10.13 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -L/opt/local/lib -Wl,-headerpad_max_install_names CMakeFiles/game_test.dir/__/__/test/test_main.cpp.o CMakeFiles/game_test.dir/__/__/test/game/dummy_test.cpp.o CMakeFiles/game_test.dir/__/__/test/game/mission_test.cpp.o CMakeFiles/game_test.dir/__/__/test/game/downgrade_test.cpp.o CMakeFiles/game_test.dir/__/__/test/game/roster_test.cpp.o CMakeFiles/game_test.dir/admin.cpp.o CMakeFiles/game_test.dir/aimast.cpp.o CMakeFiles/game_test.dir/aimis.cpp.o CMakeFiles/game_test.dir/aipur.cpp.o CMakeFiles/game_test.dir/ast0.cpp.o CMakeFiles/game_test.dir/ast1.cpp.o CMakeFiles/game_test.dir/ast2.cpp.o CMakeFiles/game_test.dir/ast3.cpp.o CMakeFiles/game_test.dir/ast4.cpp.o CMakeFiles/game_test.dir/budget.cpp.o CMakeFiles/game_test.dir/crash.cpp.o CMakeFiles/game_test.dir/crew.cpp.o CMakeFiles/game_test.dir/downgrader.cpp.o CMakeFiles/game_test.dir/draw.cpp.o CMakeFiles/game_test.dir/endgame.cpp.o CMakeFiles/game_test.dir/endianness.cpp.o CMakeFiles/game_test.dir/file.cpp.o CMakeFiles/game_test.dir/filesystem.cpp.o CMakeFiles/game_test.dir/fortify_workaround.cpp.o CMakeFiles/game_test.dir/fs.cpp.o CMakeFiles/game_test.dir/futbub.cpp.o CMakeFiles/game_test.dir/future.cpp.o CMakeFiles/game_test.dir/gamedata.cpp.o CMakeFiles/game_test.dir/game_main.cpp.o CMakeFiles/game_test.dir/gr.cpp.o CMakeFiles/game_test.dir/hardef.cpp.o CMakeFiles/game_test.dir/hardware.cpp.o CMakeFiles/game_test.dir/hardware_buttons.cpp.o CMakeFiles/game_test.dir/intel.cpp.o CMakeFiles/game_test.dir/intro.cpp.o CMakeFiles/game_test.dir/log4c.cpp.o CMakeFiles/game_test.dir/log_default.cpp.o CMakeFiles/game_test.dir/logging.cpp.o CMakeFiles/game_test.dir/mc.cpp.o CMakeFiles/game_test.dir/mc2.cpp.o CMakeFiles/game_test.dir/mis_c.cpp.o CMakeFiles/game_test.dir/mis_m.cpp.o CMakeFiles/game_test.dir/mission_util.cpp.o CMakeFiles/game_test.dir/mmfile.cpp.o CMakeFiles/game_test.dir/museum.cpp.o CMakeFiles/game_test.dir/newmis.cpp.o CMakeFiles/game_test.dir/news.cpp.o CMakeFiles/game_test.dir/news_sup.cpp.o CMakeFiles/game_test.dir/news_suq.cpp.o CMakeFiles/game_test.dir/options.cpp.o CMakeFiles/game_test.dir/pace.cpp.o CMakeFiles/game_test.dir/place.cpp.o CMakeFiles/game_test.dir/port.cpp.o CMakeFiles/game_test.dir/prefs.cpp.o CMakeFiles/game_test.dir/prest.cpp.o CMakeFiles/game_test.dir/radar.cpp.o CMakeFiles/game_test.dir/randomize.cpp.o CMakeFiles/game_test.dir/rdplex.cpp.o CMakeFiles/game_test.dir/records.cpp.o CMakeFiles/game_test.dir/replay.cpp.o CMakeFiles/game_test.dir/review.cpp.o CMakeFiles/game_test.dir/roster.cpp.o CMakeFiles/game_test.dir/roster_group.cpp.o CMakeFiles/game_test.dir/roster_entry.cpp.o CMakeFiles/game_test.dir/rush.cpp.o CMakeFiles/game_test.dir/sdlhelper.cpp.o CMakeFiles/game_test.dir/start.cpp.o CMakeFiles/game_test.dir/state_utils.cpp.o CMakeFiles/game_test.dir/utils.cpp.o CMakeFiles/game_test.dir/vab.cpp.o CMakeFiles/game_test.dir/platform_macosx/music_osx.cpp.o  -o ../../game_test   -L/opt/local/var/macports/build/_Users_rschmidt_macports_macports-ports-svn-trunk-new_games_raceintospace/raceintospace/work/build/local/lib  -Wl,-rpath,/opt/local/lib /opt/local/lib/libSDLmain.a /opt/local/lib/libSDL.dylib -framework Cocoa -logg -lvorbis -ltheora -lprotobuf /opt/local/lib/libjsoncpp.dylib -lphysfs /opt/local/lib/libz.dylib ../display/libraceintospace_display.a /opt/local/lib/libSDLmain.a /opt/local/lib/libSDL.dylib -framework Cocoa /opt/local/lib/libpng.dylib ../protobuf/libraceintospace_protobuf.a -logg -lvorbis -ltheora -lprotobuf /opt/local/lib/libjsoncpp.dylib -lphysfs /opt/local/lib/libz.dylib /opt/local/lib/libpng.dylib
ld: warning: directory not found for option '-L/opt/local/var/macports/build/_Users_rschmidt_macports_macports-ports-svn-trunk-new_games_raceintospace/raceintospace/work/build/local/lib'
Undefined symbols for architecture x86_64:
  "_DisposeMusicPlayer", referenced from:
      music_pump() in music_osx.cpp.o
  "_MusicPlayerGetTime", referenced from:
      music_pump() in music_osx.cpp.o
  "_MusicPlayerPreroll", referenced from:
      music_start_loop(music_track, int) in music_osx.cpp.o
  "_MusicPlayerSetSequence", referenced from:
      music_start_loop(music_track, int) in music_osx.cpp.o
  "_MusicPlayerSetTime", referenced from:
      music_start_loop(music_track, int) in music_osx.cpp.o
      music_stop_track(music_track) in music_osx.cpp.o
      music_pump() in music_osx.cpp.o
  "_MusicPlayerStart", referenced from:
      music_start_loop(music_track, int) in music_osx.cpp.o
  "_MusicPlayerStop", referenced from:
      music_pump() in music_osx.cpp.o
  "_MusicSequenceFileLoadData", referenced from:
      music_load(music_track) in music_osx.cpp.o
  "_MusicSequenceGetIndTrack", referenced from:
      music_start_loop(music_track, int) in music_osx.cpp.o
  "_MusicSequenceGetTrackCount", referenced from:
      music_start_loop(music_track, int) in music_osx.cpp.o
  "_MusicTrackGetProperty", referenced from:
      music_start_loop(music_track, int) in music_osx.cpp.o
  "_NewMusicPlayer", referenced from:
      music_start_loop(music_track, int) in music_osx.cpp.o
  "_NewMusicSequence", referenced from:
      music_load(music_track) in music_osx.cpp.o
  "_ugly_crash", referenced from:
      crash(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in crash.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [game_test] Error 1
```

This was already mentioned in https://github.com/raceintospace/raceintospace/issues/307#issuecomment-636640702 and https://github.com/raceintospace/raceintospace/issues/347#issuecomment-636512133 but since it is a separate issue that needs a separate solution I wanted to file it separately.

@pihhan proposed a solution in https://github.com/pemensik/raceintospace/commit/f180dd9b355716b34c1862529d25a4d36e4b751a. I don't know if that's the correct solution.

### LINKED ISSUE #551: Mac OS X build fails with CMake errors
Hi all!

Attempting to build the project on Mac OS X (Version 11.3, 13" 2020 MBP M1) results in the following error:

```
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:29 (if):
  if given arguments:

    "STREQUAL" "debug"

  Unknown arguments specified


-- Configuring incomplete, errors occurred!
See also "/Users/sean/personal_code/raceintospace-build/CMakeFiles/CMakeOutput.log".
See also "/Users/sean/personal_code/raceintospace-build/CMakeFiles/CMakeError.log".
```
Attachments:

[CMakeError.log](https://github.com/raceintospace/raceintospace/files/6651429/CMakeError.log)
[CMakeOutput.log](https://github.com/raceintospace/raceintospace/files/6651430/CMakeOutput.log)

Will be updating this issue as I continue to troubleshoot.

### PR DESCRIPTION
**Pull request by tusharpm**
Fixes #551. Fixes #364.

**Changes:**
- ~~update CMake variable (`lc_CMAKE_BUILD_TYPE`) usage in if command~~
- remove undefined function `MisPrt`
- include frameworks in `game_libraries` to fix test linking
- extract `ugly_crash` into separate file to link in tests
- add Github Actions CI workflow for macOS

**Testing done:**
- the repository builds on Intel MacBook running Big Sur.
- the game runs correctly from the build directory.
- [Sample CI run from fork](https://github.com/tusharpm/raceintospace/runs/2919885559).

**Known issues:**
- `game_test` still fails `DowngradeNextThrowTest`: TODO in future PR, considering that code is platform independent.

### CODE REVIEW

**Comment by sflynn850** [comment]
Awesome - I'll fetch this and test it tonight.

**Comment by peyre** [comment]
Ok, if you folk(s) say this is good, I'll go ahead and merge it.  Just let me know.

**Comment by sflynn850** [comment]
@tusharpm Where did you end up putting SDL.h? The include doesn't seem to be working:

`[ 25%] Built target ext_libtheora
[ 25%] Built target libs
[ 25%] Building CXX object src/display/CMakeFiles/raceintospace_display.dir/graphics.cpp.o
In file included from /Users/sean/personal_code/baris_test/raceintospace/src/display/graphics.cpp:1:
/Users/sean/personal_code/baris_test/raceintospace/src/display/graphics.h:4:10: fatal error: 'SDL/SDL.h' file not found
#include <SDL/SDL.h>
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [src/display/CMakeFiles/raceintospace_display.dir/graphics.cpp.o] Error 1
make[1]: *** [src/display/CMakeFiles/raceintospace_display.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by tusharpm** [comment]
@sflynn850 tl;dr: `SDL.h` is a header from the SDL library which is a dependency of the game.

Long version:
- I installed SDL on my machine using `brew install sdl` (the README mentions the other dependencies such as CMake and boost also).
- The path for the header on my machine is `/usr/local/Cellar/sdl/1.2.15_3/include/SDL/SDL.h`; also available from `/usr/local/include/SDL/SDL.h` by symlinks. [This information is useful if you're working on the SDL linkage.]
- After installing SDL on your machine (using the brew command mentioned above), CMake might not run the SDL detection logic again. One way to sidestep that is to delete the existing build directory, as mentioned in the README after the git clone step.

**Pull request merged**
