### PR TITLE
Add JSON serialization for game data and save games

### LINKED ISSUE #21: Decouple save games from internal data structures
I'd really like to shuffle around the members of `struct BuzzData`, but I can't because the game assumes old save files conform to that structure layout. We could change the magic number every time we change the save game format, but that's a poor solution. So, let's talk about better solutions.
## Protocol Buffers

[Protocol Buffers](http://code.google.com/p/protobuf/) were created to address this need to sanely version data structures.
- Pro: it lets us be explicit about how data should now be laid out without forgetting about how it used to be structured
- Pro: it cleanly separates the definition of an interchange data structure from the code that accesses it
- Pro: it would be particularly appropriate for use over a network (play-by-mail/Internet multiplayer)
- Con: it's another library
## jsoncpp

Another option would be to use [jsoncpp](http://jsoncpp.sourceforge.net/)'s coercion and default value support:

```
m_name = json_object["name"].asString();
m_female = json_object.get("female", false).asBool();
m_capsule = json_object.get("capsule", 0).asInt();
m_lunar = json_object.get("lunar", 0).asInt();
m_eva = json_object.get("eva", 0).asInt();
m_docking = json_object.get("docking", 0).asInt();
m_endurance = json_object.get("endurance", 0).asInt();
```
- Pro: we already have jsoncpp
- Con: we have to consciously worry about versioning in the code
- Con: ...and we're going to get it wrong somewhere

Even if we pick Protocol Buffers for save games, it shouldn't replace jsoncpp for game data. Game data should be user-editable, and JSON wins there. Moreover, versioning is unimportant since we can to change both the game data and the code that reads it simultaneously. Save games live on-disk, and we're expecting saves to be written by one version and read by another.

Thoughts?

### PR DESCRIPTION
**Pull request by hweimer**
This PR introduces serialization for both game data and save game files by handling them as JSON files when written to/read from disk, using the Cereal library. Char arrays are serialized into JSON strings with loading ensuring that they fit into the respective buffer. Simple numeric arrays are serialized as JSON vectors. Save game files are additionally compressed using zlib before writing.

This is a rather minimal approach in that only the game data structure plus replay and event data get serialized so far. However, it should be rather straightforward to extend this to other areas such as mission data files by adding a serialize function to the struct of interest. To this end, serialize.h includes some helper macros for string and vector serialization for C-arrays.

Fixes #21.

### CODE REVIEW

**Comment by rnyoakum** [comment]
The cereal header and move to C++11 should be added to this pull request as well, so they get committed together.

**Comment by hweimer** [comment]
>The cereal header and move to C++11 should be added to this pull request as well, so they get committed together.

I've added both things, and at least on my machine the build runs successfully even if Cereal has not been installed before.

**Comment by pemensik** [comment]
Is another serialization library required? I think we already have jsoncpp library for handling json. And we also require protobuf. Do we have specific reason to choose yet another library? More different libraries makes it harder to build from source.

**Comment by rnyoakum** [comment]
There's a discussion of using Cereal in #21. The idea was to move to C++11, use Cereal as a serialization library and drop Protocol Buffers support. If you have any opinions or disagree, I'd love to hear it.

Because of the need to hash out any such issues, I wasn't merging this pull request until after the next release.

**Comment by hweimer** [comment]
The problem with both protobuf and jsoncpp is that you can't directly serialize from the current Data struct. So, using them would mean to change almost every line of code of the entire game. Frankly speaking, I don't see this as a realistic option. With Cereal, you just need to add a serialize method to the struct and that's it. Additionally, Cereal is a header-only library, so I don't see how this makes building from source any harder (other than requiring a C++11 compiler).

**Comment by hweimer** [comment]
Given that there is now an growing list of issues that can be fixed much easier when this PR gets merged, wouldn't it make sense to merge it into a new branch to keep things going? Alternatively, one could also create a separate release branch in which #416 gets taken care of.

**Comment by peyre** [comment]
It sounds good to me.  I'm inclined, though, to defer to the programmers in the group, as I don't necessarily understand the potential implications of this one.

**Comment by hweimer** [comment]
Closed by #655.

**Pull request closed without merging**
