### PR TITLE
Vhptr reduction

### PR DESCRIPTION
**Pull request by pemensik**
Hello, I found some time after long pause for the project. I tried to reduce usage of global vhptr for various bitmap copying. Instead I created just buffer or DisplayContext structure for local passing of variables for rendering on a page. It seems a bit more clear what is used and what palette source is used.

Also preferences was a bit rewritten to use draw instead of copyTo from vhptr. Found some strange artifact on USA human/computer toggle, not yet fixed. But otherwise it should work. Would someone have a while to look at my changes, whether they make sense?

### CODE REVIEW

**Comment by rnyoakum** [comment]
I've looked over your commit, and it looks pretty good. In my examination of the code I've concluded vhptr was frequently being used to avoid creating/destroying 320x200 px buffer surfaces. In 2020, that's less of a problem than the confusion of trying to monitor what vhptr is being used for at any given moment, and what restrictions are being placed on it by other sections of code.

The only issues I noticed are in your changes to prefs.cpp. You're loading the preferences image into the DisplayContext in Prefs() right before calling DispPrefs():
```
    boost::shared_ptr<display::PalettizedSurface> prefs_image(Filesystem::readImage("images/preferences.png"));
    dctx.prefs_image = prefs_image;

    /* Data->Def.Sound=Data->Def.Music=1; */
    DrawPrefs(where, hum1, hum2, dctx);
```
which also loads images/preferences.png into the DisplayContext. It's a duplicate file read, but shouldn't cause any harm.

Also, I noticed you're passing the DisplayContext into HModel. I'm guessing that you forgot to remove the parameter once you realized the update to vhptr could be eliminated when replaced by dctx?

**Comment by peyre** [comment]
This is a little too back-end for me to grasp, but I'm glad you're taking care of these kinds of things.  Good to see you back, Petr.

**Comment by peyre** [comment]
Thanks for taking care of this, Ryan.

**Comment by pemensik** [comment]
Thanks for comments, you are right, those are leftovers from previous try. Ok, closing this, since it is merged to master anyway.

**Pull request merged**
