### PR TITLE
Fix endianness swap

### PR DESCRIPTION
**Pull request by rnyoakum**
Fixes a bug in the endianness swapping and swaps several more - apparently overlooked - fields.

### CODE REVIEW

**Comment by peyre** [comment]
Good work!

**Comment by peyre** [comment]
Say, did this bug make a visible change in the game, something that a player would notice?

**Comment by rnyoakum** [comment]
Not normally, no. It's not a bug I was hunting; I found it while testing some new code.

The bug is only relevant when loading game data when you would have to perform an endianness swap - if the game data is stored using a different endianness than your system uses. The game data is stored in little endian format, which is what x86 systems use. So my computer - and likely yours - never calls this code. The particular changes I made (without checking) would probably only show up when loading save game file, and only if that save game was transferred to a computer with a different architecture. So it's a _very_ niche issue.

**Comment by peyre** [comment]
Good to know, thanks!  Every little improvement helps.

**Pull request merged**
