### PR TITLE
Add appdata description

### PR DESCRIPTION
**Pull request by pemensik**
Provides some metadata for package.
Should display nicer info in a package manager.

Used again descriptions from manual. Adds [package metadata](https://docs.fedoraproject.org/en-US/packaging-guidelines/AppData/) for nicer integration of package.

Because I used content I did not write myself and it is requested to provide the description with license suitable for documentation, I request review. Especially @peyre should review.

### CODE REVIEW

**Comment by peyre** [comment]
License stuff we might want to run past Michael, since he's one of the copyright holders.

**Comment by peyre** [comment]
So these two paragraphs were taken from the Intro to the manual document.  Not a bad idea.

**Comment by pemensik** [comment]
Just to be clear, I am not asking to change the license of the whole package. I am asking just different license for the metadata file this adds. Should help to make information about it more available.

**Comment by pemensik** [comment]
These metadata are required to show in [Gnome Software](https://wiki.gnome.org/Apps/Software). However I have issues getting them displayed. I wanted to present screenshot how it would look like, but does not yet work to me.

**Pull request merged**
