### PR TITLE
Hires icon

### PR DESCRIPTION
**Pull request by pemensik**
Hi guys. I have been playing with [flatpak package preparation](https://github.com/flathub/flathub/pull/1822), when I found current game icon is really low resolution. I attempted to create similar icon from startup screen, but in higher resolution.

It might be funny to have hi-res icon and low resolution game, I admit it is unimportant.
I would like to ask, whether you like it. And if possible, whether would it show in applications launcher in your distribution, when installed to /usr/local by default.

Attached also GIMP project, If anyone wanted to modify it.

### CODE REVIEW

**Comment by peyre** [comment]
I'm not particular.  The current image seems roughly in keeping for the rest of the game, but if you want to make it higher-res I don't object.  It's modified from the original anyway (to remove Buzz's name, and add the Voskhod spacewalk).

**Comment by barthalion** [comment]
As a reference, this is how it looks like in the store: https://flathub.org/apps/details/org.raceintospace.Raceintospace

Most likely it looks the same in GNOME Software and other native frontends.

**Comment by rnyoakum** [comment]
The new hi-res looks good to me :)

**Comment by peyre** [comment]
I compared the two - and when I simply resampled our current one to 200%, it looks almost exactly identical.  I think that's all they did was to resize the current photo.  But I don't object to people changing it to one that they think looks better.

**Comment by rnyoakum** [comment]
> I compared the two - and when I simply resampled our current one to 200%, it looks almost exactly identical. I think that's all they did was to resize the current photo.

I don't think they are using the new photo that Petr created, I think flathub _is_ resizing the current photo. Petr's new version doesn't have the yellow border around Race Into Space, for one.

**Comment by pemensik** [comment]
Sure, I have not yet used hi-res icon. It is not yet in master branch. Check our [new flathub page](https://flathub.org/apps/details/org.raceintospace.Raceintospace). By the way, I noticed only much later, we already [have square icon](https://avatars3.githubusercontent.com/u/1273702?s=200&v=4) with good enough resolution. It can be just reduced in size.

**Comment by pemensik** [comment]
So maybe my own icon should not be used and instead use higher resolution icon already existing. Just should add it to repository, so it can be installed. Do we know, who made it?

**Comment by pemensik** [comment]
I have pushed icon used here on github. I think it would be nice, is just higher resolution of current (linux) small icon. That means my own attempt would not be necessary.

**Pull request closed without merging**
