### PR TITLE
Use shared libraries, compile on Fedora

### PR DESCRIPTION
**Pull request by pemensik**
Contains two changes.

- First is required to compile on Fedora. It has different jsoncpp package directory. It would not compile on Fedora without BUILD_JSONCPP.
- Second is ability to compile with shared libphysfs instead of local shared version. Still is default to use local build (hope there is good reason for it?), but allows override from cmake. Just define -DBUILD_PHYSFS=OFF.

I would like to create package for this project on Fedora. It is required all libraries are using shared versions on the system. It still compiles on Debian and now also on Fedora 29.

### CODE REVIEW

**Comment by peyre** [comment]
Thank you, Petr.  When we do release(s) of the game, I would like to include a Fedora installer as well as a Debian/Ubuntu one (as well as Windows and, ideally, Mac).

**Comment by pemensik** [comment]
Hi. There is not really need for any installer on Fedora. On the contrary. I am working on ability to package this project as Fedora package. You could install it just like any other package:

    dnf install raceintospace

I think that is the main power of open source. My changes are required to make it pass requirements for inclusion. It does not solve Windows installer of course, programs are usually installed different way.

**Comment by peyre** [comment]
Well, all right.  Sounds good to me.  So would you be interested in joining RIS development?

    On Friday, July 19, 2019, 4:24:25 PM PDT, Petr Menšík <notifications@github.com> wrote:  
 
 
Hi. There is not really need for any installer on Fedora. On the contrary. I am working on ability to package this project as Fedora package. You could install it just like any other package:
dnf install raceintospace

I think that is the main power of open source. My changes are required to make it pass requirements for inclusion. It does not solve Windows installer of course, programs are usually installed different way.

**Comment by pemensik** [comment]
Just for the record, made package [Fedora package build on COPR](https://copr.fedorainfracloud.org/coprs/pemensik/raceintospace/). If I have spare time, I may be willing to invest some on the project. But I cannot promise much.

**Comment by peyre** [comment]
Not to worry.  I can add you to the project if you'd like to work on the game, but I don't want to pressure you.

    On Sunday, July 21, 2019, 8:51:52 AM PDT, Petr Menšík <notifications@github.com> wrote:  
 
 
Just for the record, made package Fedora package build on COPR. If I have spare time, I may be willing to invest some on the project. But I cannot promise much.

**Pull request merged**
