### PR TITLE
Add play-by-mail mode

### LINKED ISSUE #131: Play-by-Email (PBEM) missing
Stumbled across this project today, and excitedly cloned it. Building was easy on my Fedora box.

I was looking forward to playing this game asynchronously with friends using the PBEM game mode, but I can't seem to find it.

Any idea where it is?

### PR DESCRIPTION
**Pull request by hweimer**
Bringing back play-by-mail by adding a new game mode that sets the MAIL global variable to 0 on U.S. turns and 1 on Soviet turns. The main strategy is that U.S. missions are launched twice; once after the U.S. turn to determine the outcome, and a second time after the Soviet turn (reusing the mission events from the U.S. turn) to determine Prestige. Before the save file is sent to the Soviet side, Data->Prestige and the U.S. mission counter are restored to their previous states.

At the beginning of the turn, the U.S. player is informed about the Prestige results of the previous turn and about any Prestige Firsts acheived by the Soviet side. The Soviet side sees the U.S. Prestige Firsts during the Soviet mission resolution, i.e., like when playing against the AI.

Turns are played the usual way, with a file saving dialog appearing after ending the turn. As the Data struct contains two new fields for mission resolution, this breaks save game compatibility.

At some points, I have hit some ancient codepaths, like when starting the mail game by calling Prefs(3). While things seem to work, there might be unintended side effects. Therefore, expect bugs.

Resolves #131 and #346.

### CODE REVIEW

**Comment by peyre** [comment]
This is exciting!  Am I right in thinking this is all working as far as you know?  Normally our programmers merge the pull requests, but they're quiet at the moment.  I'd merge this one here and now but I'm not in a position to really test it before the weekend.  Have you done any testing on it yourself, actually played part of a PBEM game?

**Comment by hweimer** [comment]
I ran a couple of tests that seemed to work fine, but now I have encountered an issue with equipment. Probably something like U.S. equipment being subtracted twice. So better wait to merge until this is resolved.

**Comment by peyre** [comment]
Thanks for the heads-up!  Keep me posted.

**Comment by hweimer** [comment]
It was exactly one of these ancient codepaths. Removing the tests for the MAIL global variable in AstroTurn() fixes the problem and also ensures that astronaut data is updated correctly. The diff looks much bigger than it is because of the changed indentation. At the end of the day, it's just something like three if clauses being removed. 

I just played a mail game into the early 60s and didn't notice anything odd.

**Pull request merged**
