### PR TITLE
Dat to json

### PR DESCRIPTION
**Pull request by alsed**
binaries files converted to json:
- vtable.dat (coordinate data for VAB components).
- ntable.dat (budget modification table).
- letter.dat (font drawing parameters).
- usa_port.dat, sov_port.dat (spaceport screen drawing parameters).
- event.dat (text for news events).
- news.dat (text for history and astronauts news).
- endgame.dat (text for endgame).
- p_rev.dat (text for presidential review).
- mission.dat (data parameters for  missions).
- missSteps.dat (data for mission splines).
- portbut.but (port buttons pixel data).
- liftoff.abz (component animation in the failure screen).

changes:
- gameplay: now player and rival use the same table (1) for budget modification.
- sprites for spaceports had been implemented, previously they were loaded from the dat file.
- sprite animations for failure screen had been implemented.
- the position data of the VAB (Vehicule Assembly) sprites have been moved to json format.
- budget tables have been moved to json format.
- mission codes and step data have been moved to json format.
- text for events, news, endgame and presidental review have been moved to json format.
- mission codes and data step data are now uploaded in mission_utils.cpp: "GetMissionData". 
- in future.cpp, functions "UpSearchRout" and "DownSearchRout" remade, function "missionName" renamed "DrawMissionName" to avoid confusion with missionName variable, and function "SetMissionParameters" eliminated for redundancy.
- in port.cpp, function "PortPlace" renamed "LoadImg" for clarity of purpose.
- In mis_c.cpp: the failure animations have been implemented from the exported images,  a (nice) blue color has been added for the background, all frames for the animation are now loaded into a cache, and then are called for drawing, several new functions created for deserialization and animation.
- in mmfiles.cpp, several info calls moved to TRACE.
- liftoff.abz; the data has been serialized and the animation frames has been exported. The palette was faked with a gray palette scale with modified brightness and contrast parameters to resemble the original.
- images for faces, rd, patches, port, portbut, mhist, aprog and letter has been moved to its own folders.

### CODE REVIEW

**Comment by peyre** [comment]
My goodness you've been busy!  Say alsed, could we add a variable to the newscasts for "Effect" or somesuch, so we can color-code newscasts?  One color for those that negatively affect you, another for those that don't affect it at all, and another color for those that positively affect it?  It could be an integer, set to -1, 0, 1 - or maybe 0, 1, 2.

**Comment by alsed** [comment]
I have been indeed :)
The events could be color-coded positive/negative. First we would need to "flag" them as such. 
I think the game already flags the events in the code (and tries to not overdo bad events), but doesn't seems to work properly, as your [discussion](https://github.com/raceintospace/raceintospace/discussions/542) states. We could also work on to tackle this first.
Events doesn't work as straighforward as I would want to, but it can be possible.
As you state in the manual, some events have no effect. I consider this a bug that needs to be solved, via implementation or modification.

**Comment by peyre** [comment]
I'm actually ok with not fixing the remaining newscasts that don't work (or at least many of them), because I think they would hurt gameplay.  In particular, if nothing else, I think we should leave the "50% chance of exploding on next launch" one TF alone.  Also, if we were to fix the one that required you fly Duration E, we'd need to throw the player a bone if they're flying minishuttles - maybe allow the minishuttle to fly a (barely) Dur E mission once they get the newscast.

**Comment by alsed** [comment]
With the text serialized, we have more options available to fix that issue, let's say 50% chance of explosion is preposterous, what about 40%... or even 30%? 
now the decision seem more interesting, (the idea behind it was to tempt a risk)
We can have a fixed number, we can have a dice rolled or we can even _change it completely_ to something else, we can fix it.

**Comment by peyre** [comment]
Well...if people think we should actually implement this, I suppose we could go ahead with it.  The bit about damaged equipment (pay xMB or lose y% Safety) wasn't working initially, and when Nicolas implemented it, I was against doing so - but I think it was an improvement.  So maybe fixing this "next launch may explode" newscast is a good idea too.  I don't have strong feelings about what the exact number should be.  Given that the audio for the newscast says it's 50% we might want to leave it at that.

Changing it completely is an intriguing idea, though I don't know what we'd change it to - and there's the issue with the audio, too.

**Pull request merged**
