### PR TITLE
Fix Apollo DM spoofing

### PR DESCRIPTION
**Pull request by rnyoakum**
Fixes an error where Apollo/Soyuz missions get credited with a 'spoofed' docking module regardless of the DM's presence, preventing the player's DM inventory from being decremented. This would affect all missions with both an Apollo/Soyuz & DM on the first launch of a mission. The Apollo/Soyuz should only 'spoof' a docking module on missions with a Lunar Module.

### CODE REVIEW

**Comment by peyre** [comment]
Marvelous!  Is this the problem I reported where somehow the game sticks at 2 DMs in your inventory, no matter how many times you use them?  If so, I think I may have seen it happen with the shuttles as well.

**Comment by rnyoakum** [comment]
Do you mean that you have seen the game stick at 2 DMs when flying shuttle missions, or stick at 2 shuttles when flying shuttle missions?

**Comment by peyre** [comment]
Oh!  The former - that I think I've seen it stick at 2 DMs when flying shuttles.

**Comment by peyre** [comment]
Ok, I just playtested it.  I flew two U Docking missions in a turn, and the following turn I had zero DMs, just as I should.  I'm guessing we're ok here.

**Pull request merged**
