### PR TITLE
Attempt to cleanup the build-instructions for Windows

### PR DESCRIPTION
**Pull request by sundhaug92**

### CODE REVIEW

**Comment by peyre** [comment]
Hello Martin!  This is a surprise.  Interested in helping us develop Race Into Space?

**Comment by sundhaug92** [comment]
@peyre I'm not sure how much help I can be, I haven't even played the game more than twice or something

**Comment by peyre** [comment]
Well we'd be glad to have you on board if you'd like to help develop it.  There are only 2 of us currently.

**Comment by sundhaug92** [comment]
Thanks @peyre, how do you feel about merging this PR?

**Pull request merged**
