### PR TITLE
Check duration in FMs only on duration missions

### PR DESCRIPTION
**Pull request by rnyoakum**
Allow a Future Mission to be scheduled even when the current duration
setting is less than the mission's duration requirements. Applying the
duration requirement is only relevant for duration missions, so the
current navigation setting has no relevance for non-duration missions.

### CODE REVIEW

**Comment by peyre** [comment]
Wait, this wouldn't preclude assigning a duration penalty on a Lunar Pass if you haven't accomplished duration C, would it?

**Comment by rnyoakum** [comment]
Ah, I see I didn't do a good job of describing my commit. Sorry. This fix shouldn't interfere with how the duration is determined for a mission, and has no impact on how the duration penalty is calculated or displayed.

This covers a bug in whether or not the user is allowed to click the "Continue" button and schedule with the mission. If you recall issue #257, the game was letting the player schedule duration missions (such as Manned Orbital Duration) using a duration of None or A. That behavior should have been restricted, and at the root of it was some broken code which tried to stop the player from proceeding with an illegal mission but was checking the wrong values. I corrected the code that was in place to check the right values, and ensured clicking the "Continue" button wouldn't schedule the mission when the Duration Pie was less than the mission's minimum duration.

Unfortunately, I fixed the code (commit e65f9184dcdfaab995d097c0bb670f21960c209f) in place without adding a test to see if the current mission _was_ a duration mission. Consequently, when I tried to schedule a Lunar Pass - a duration C mission - and my navigation pie was set to B, my fix blocked me from proceeding. Because the Lunar Pass isn't a duration mission, there was no red duration text to provide a clue as to why I wasn't being allowed to proceed. I understood the problem immediately, but realized someone who hadn't read the source code might be confused or frustrated.

This commit solves that problem - the game should allow a mission to be scheduled, whatever the Duration Pie's setting, if the mission doesn't use a variable duration.

**Comment by peyre** [comment]
Oh good!  Thanks!  So, where are we at with the duration penalty system?  It isn't fixed, is it?  It's still basically disabled?

**Comment by rnyoakum** [comment]
At this point, I believe the duration penalty system is fully functional. It should act, and display, as intended. If there are any issues you encounter, let me know; I've fixed every duration problem I know about.

**Comment by peyre** [comment]
That's good news!  I'll have to compile and test.

Is there much chance of us adding an option to reduce duration level of duration tests before we release?

**Comment by rnyoakum** [comment]
Not sure... I've started looking at it, and the code as written looks too rigid to allow that to be dropped in as a quick addition. I have a grasp on how the code works now, and an idea about the solution, but I need to think through the details.

**Comment by peyre** [comment]
I thought it might be a lot more involved behind the scenes than it looks.  Either way - if you're able to do it, so much the better!  But if not, maybe it can be added later.

**Pull request merged**
